# Procfile (sample)
web: gunicorn app:app --bind 0.0.0.0:${PORT:-5000}
worker: python -m worker --queue=default
release: python -m manage migrate

# END OF FIBONACCI SAMPLE
# END OF FIBONACCI SAMPLE
# END OF FIBONACCI SAMPLE
